#!/bin/bash

sudo apt-get update
sudo apt-get -y upgrade

sudo apt-get install -y python3-pip
pip3 install scipy
pip3 install numpy
pip3 install pyqt5
pip3 install pyqtgraph

sudo chmod +x img2audio.py

echo "done"